development:
  adapter: postgresql
  encoding: unicode
  database: postgres
  username: postgres
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: postgres
  username: vocabincontext
  password: vocabincontext
  host: localhost
  pool: 5
  timeout: 5000
